# Generated by Django 6.0.6 on 2026-07-25 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surah',
            options={'ordering': ['number']},
        ),
        migrations.AddField(
            model_name='surah',
            name='bismillah',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='surah',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='surah',
            name='revelation_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surah',
            name='revelation_type',
            field=models.CharField(choices=[('MECCAN', 'Mecquoise'), ('MEDINAN', 'Médinoise')], default='MECCAN', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='matricule',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='surah',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='surah',
            name='name_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='surah',
            name='number',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='surah',
            name='total_verses',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse_number', models.PositiveSmallIntegerField()),
                ('text_ar', models.TextField()),
                ('text_fr', models.TextField(blank=True)),
                ('text_en', models.TextField(blank=True)),
                ('juz', models.PositiveSmallIntegerField()),
                ('hizb', models.PositiveSmallIntegerField()),
                ('page', models.PositiveSmallIntegerField()),
                ('sajda', models.BooleanField(default=False)),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='core.surah')),
            ],
            options={
                'ordering': ['surah', 'verse_number'],
                'constraints': [models.UniqueConstraint(fields=('surah', 'verse_number'), name='unique_surah_verse')],
            },
        ),
    ]
