# Generated by Django 6.0.6 on 2026-08-04 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_surah_options_surah_bismillah_surah_name_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['level_number'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=20)),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.curriculumlevel')),
            ],
            options={
                'ordering': ['level', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('validation_method', models.CharField(choices=[('PRACTICAL', 'Pratique'), ('ORAL', 'Oral'), ('WRITTEN', 'Écrit'), ('QUIZ', 'Quiz')], default='PRACTICAL', max_length=30)),
                ('is_gate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='core.curriculummodule')),
            ],
            options={
                'ordering': ['module', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StudentCurriculumProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Non démarré'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé'), ('REVIEW', 'À revoir')], default='NOT_STARTED', max_length=20)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='core.curriculumcompetency')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_progress', to='core.student')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='curriculummodule',
            constraint=models.UniqueConstraint(fields=('level', 'order'), name='unique_module_order_per_level'),
        ),
        migrations.AddConstraint(
            model_name='curriculumcompetency',
            constraint=models.UniqueConstraint(fields=('module', 'order'), name='unique_competency_order_per_module'),
        ),
        migrations.AddConstraint(
            model_name='studentcurriculumprogress',
            constraint=models.UniqueConstraint(fields=('student', 'competency'), name='unique_student_competency_progress'),
        ),
    ]
