# Generated by Django 6.0.6 on 2026-08-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_curriculumlevel_curriculummodule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
