# Generated by Django 6.0.6 on 2026-08-04 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_student_matricule'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=10)),
                ('is_required', models.BooleanField(default=True)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.curriculummodule')),
            ],
            options={
                'ordering': ['module', 'order', 'title'],
                'constraints': [models.UniqueConstraint(fields=('module', 'order'), name='unique_lesson_order_per_module')],
            },
        ),
    ]
