# Generated by Django 6.0.6 on 2026-08-04 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_studentevaluation_studentgroup_studentobservation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLevelValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PASSED', 'Validé'), ('FAILED', 'Échoué')], default='PENDING', max_length=20)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_validations', to='core.curriculumlevel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_validations', to='core.student')),
            ],
            options={
                'ordering': ['-validated_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'level'), name='unique_student_level_validation')],
            },
        ),
    ]
