# Generated by Django 6.0.6 on 2026-08-11 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_studentlevelvalidation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(default='Arabe', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['level', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumBookContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(choices=[('TEXT', 'Texte'), ('EXERCISE', 'Exercice'), ('RULE', 'Règle'), ('EXAMPLE', 'Exemple'), ('MEMORIZATION', 'Mémorisation'), ('PRACTICE', 'Pratique')], default='TEXT', max_length=20)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_required', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumBookSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['book', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('TAJWEED', 'Tajwid'), ('HIFZ', 'Hifz'), ('FIQH', 'Fiqh'), ('HADITH', 'Hadith'), ('TAFSIR', 'Tafsir'), ('NAHW', 'Nahw'), ('SIRAH', 'Sira')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LessonBookReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Non démarrée'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée'), ('REVIEW', 'À revoir')], default='NOT_STARTED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='curriculumcompetency',
            options={'ordering': ['lesson', 'order', 'title']},
        ),
        migrations.RemoveConstraint(
            model_name='curriculumcompetency',
            name='unique_competency_order_per_module',
        ),
        migrations.AddField(
            model_name='curriculumcompetency',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='core.curriculumlesson'),
        ),
        migrations.AddField(
            model_name='curriculumlesson',
            name='objectives',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='darasasession',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='darasa_sessions', to='core.curriculumlesson'),
        ),
        migrations.AddField(
            model_name='darasasession',
            name='session_type',
            field=models.CharField(choices=[('QURAN', 'Coran'), ('PRAYER', 'Prière'), ('WUDU', 'Ablution'), ('TAJWEED', 'Tajwid'), ('HADITH', 'Hadith'), ('FIQH', 'Fiqh'), ('SIRAH', 'Sira'), ('DUA', 'Invocations'), ('ARABIC', 'Arabe')], default='QURAN', max_length=20),
        ),
        migrations.AddField(
            model_name='studentlevelvalidation',
            name='evaluated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level_validations_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentlevelvalidation',
            name='oral_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentlevelvalidation',
            name='practical_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='curriculumcompetency',
            constraint=models.UniqueConstraint(fields=('lesson', 'order'), name='unique_competency_order_per_module'),
        ),
        migrations.AddField(
            model_name='curriculumbook',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='core.curriculumlevel'),
        ),
        migrations.AddField(
            model_name='curriculumbooksection',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.curriculumbook'),
        ),
        migrations.AddField(
            model_name='curriculumbookcontent',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='core.curriculumbooksection'),
        ),
        migrations.AddField(
            model_name='curriculumspecialization',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='core.curriculumlevel'),
        ),
        migrations.AddField(
            model_name='lessonbookreference',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_references', to='core.curriculumbook'),
        ),
        migrations.AddField(
            model_name='lessonbookreference',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_references', to='core.curriculumlesson'),
        ),
        migrations.AddField(
            model_name='lessonbookreference',
            name='section_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='references_starting_here', to='core.curriculumbooksection'),
        ),
        migrations.AddField(
            model_name='studentlessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='core.curriculumlesson'),
        ),
        migrations.AddField(
            model_name='studentlessonprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='core.student'),
        ),
        migrations.AddField(
            model_name='studentspecialization',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.curriculumspecialization'),
        ),
        migrations.AddField(
            model_name='studentspecialization',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='core.student'),
        ),
        migrations.RemoveField(
            model_name='curriculumcompetency',
            name='module',
        ),
        migrations.AddConstraint(
            model_name='curriculumbooksection',
            constraint=models.UniqueConstraint(fields=('book', 'order'), name='unique_book_section_order'),
        ),
        migrations.AddConstraint(
            model_name='curriculumbookcontent',
            constraint=models.UniqueConstraint(fields=('section', 'order'), name='unique_book_content_order'),
        ),
        migrations.AddConstraint(
            model_name='lessonbookreference',
            constraint=models.UniqueConstraint(fields=('lesson', 'book'), name='unique_lesson_book_reference'),
        ),
        migrations.AddConstraint(
            model_name='studentlessonprogress',
            constraint=models.UniqueConstraint(fields=('student', 'lesson'), name='unique_student_lesson_progress'),
        ),
        migrations.AddConstraint(
            model_name='studentspecialization',
            constraint=models.UniqueConstraint(fields=('student', 'specialization'), name='unique_student_specialization'),
        ),
    ]
