# Generated by Django 6.0.6 on 2026-08-11 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_curriculumbook_curriculumbookcontent_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='curriculumcompetency',
            name='unique_competency_order_per_module',
        ),
        migrations.AlterField(
            model_name='curriculumcompetency',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='core.curriculumlesson'),
        ),
        migrations.AddConstraint(
            model_name='curriculumcompetency',
            constraint=models.UniqueConstraint(fields=('lesson', 'order'), name='unique_competency_order_per_lesson'),
        ),
    ]
