# Generated by Django 6.0.2 on 2026-08-15 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_curriculumcompetency_unique_competency_order_per_module_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='darasasession',
            options={'ordering': ['-date', '-start_time']},
        ),
        migrations.AddField(
            model_name='darasasession',
            name='competency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='darasa_sessions', to='core.curriculumcompetency'),
        ),
        migrations.AlterField(
            model_name='darasasession',
            name='surah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='darasa_sessions', to='core.surah'),
        ),
        migrations.AlterField(
            model_name='darasasession',
            name='verse_end',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='darasasession',
            name='verse_start',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
